project:
  type: website

website:
  sidebar:
    - id: "main"
      contents:
        - section: "Documentation"
          contents:
            - reference/index.qmd

quartodoc:
  package: "multiband-regression" # name of the package
  source_dir: "mb_regression" # as the source code is within this folder

  title: "Documentation for the multiband-regression module"

  options:
    signature_name: full

  # write sidebar where quartodoc writes its content without impacting quarto
  sidebar:
    file: "reference/_multiband_regression_sidebar.yml"

  sections:
    - title: "The multiband-regression module"
      desc: |
        :::{.callout-info}
        The github repository for this module is located at:
        [https://github.com/bsdlab/dp-multiband-regression](https://github.com/bsdlab/dp-multiband-regression)
        :::
      contents:
        - main.init_lsl_outlet
        - main.process_loop
        - main.run_multiband_regression