[filter_design]
type = 'butter'
order = 8

[frequency_bands]
theta = [5, 8]
alpha = [8, 13]
beta_low = [13, 20]
beta_high = [20, 30]
gamma_low = [30, 45]   # stopping at 45 to not deal with notch filter yet
gamma_high = [55, 70]   

[stream_to_query]
stream = "AODataStream"   # just one stream here atm
# stream = "mock_EEG_stream"   # just one stream here atm
buffer_size_s = 30         # buffer size in seconds

# just get the ecog channels - array indeces
channels = [16, 17, 18, 19]

[lsl_outlet]
name = "decoded_ecog"
nominal_freq_hz = 5
format = "float32"
type = "decoder_output"

[others]
warm_up_time_s = 1.5     # no signal is forwarded in this time which is used as filter warm-up
